spring:
 main:
  banner-mode: log
 hibernate:
  ddl: create-drop
 application:
  name: ilda
 boot:
  admin:
   url: http://localhost:8083
   client:
    serviceUrl: http://localhost:8083
 output:
  ansi:
   enabled: detect
management:
 port: 8084
 address: 0.0.0.0
 context-path: /supervision
multipart:
  max-file-size: 10Mb
  max-request-size: 10Mb
#SERVER
server:
 port: 8083
 session-timeout: 300
 tomcat.uri-encoding: UTF-8
 compression:
  enabled: true
  mime-types: application/json
ilda:
 show:
  sql: true
datasource:
 initialize: false
 ilda:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:ILDA;DB_CLOSE_DELAY=-1;
  username: sa
  password:
#LOGS
logging:
 level:
  org:
   springframework: 
    test:
     context: DEBUG
    security: DEBUG